import { Commerce, Promotion, Tenant } from '@/types';

export const MOCK_TENANT: Tenant = {
  id: 'homa_mall',
  name: 'HOMA Mall',
  slug: 'homa-mall',
  description: 'El centro comercial más moderno de Carlos Paz. Más de 60 locales comerciales, gastronomía, entretenimiento y servicios en un solo lugar.',
  logoUrl: '',
  primaryColor: '#1e293b',
  accentColor: '#f59e0b',
  location: 'Carlos Paz, Córdoba',
  whatsapp: '5493541000000',
  email: 'info@homamall.com.ar',
  instagram: 'homamall',
  status: 'activo',
  createdAt: '2024-01-01',
};

export const MOCK_COMMERCES: Commerce[] = [
  {
    id: '1',
    tenantId: 'homa_mall',
    name: 'La Birra Craft',
    slug: 'la-birra-craft',
    category: 'Gastronomía',
    subcategory: 'Cervecería',
    locationCode: 'L-101',
    description: 'Cervecería artesanal con las mejores birras locales e importadas. Ideal para después del trabajo o una salida con amigos.',
    logoUrl: '',
    photos: [],
    whatsapp: '5493541111111',
    instagram: 'labirracraft',
    schedule: 'Lunes a Domingo 12:00 - 00:00',
    publicStatus: 'verificado',
    internalStatus: 'documentacion_completa',
    documentationStatus: 'completa',
    protectionStatus: 'protegido',
    isFeatured: true,
    createdAt: '2024-01-15',
    updatedAt: '2024-03-01',
  },
  {
    id: '2',
    tenantId: 'homa_mall',
    name: 'TechZone',
    slug: 'techzone',
    category: 'Tecnología',
    subcategory: 'Electrónica',
    locationCode: 'L-215',
    description: 'Todo en tecnología: celulares, computadoras, accesorios y servicio técnico. Las mejores marcas al mejor precio.',
    logoUrl: '',
    photos: [],
    whatsapp: '5493541222222',
    instagram: 'techzonecarlospaz',
    schedule: 'Lunes a Sábado 09:00 - 21:00 | Domingo 10:00 - 20:00',
    publicStatus: 'publicado',
    internalStatus: 'documentacion_completa',
    documentationStatus: 'completa',
    protectionStatus: 'parcial',
    isFeatured: false,
    createdAt: '2024-02-01',
    updatedAt: '2024-03-05',
  },
  {
    id: '3',
    tenantId: 'homa_mall',
    name: 'Moda Bella',
    slug: 'moda-bella',
    category: 'Indumentaria',
    subcategory: 'Moda femenina',
    locationCode: 'L-308',
    description: 'Las últimas tendencias en moda femenina. Ropa, accesorios y calzado para cada ocasión.',
    logoUrl: '',
    photos: [],
    whatsapp: '5493541333333',
    instagram: 'modabellacpaz',
    schedule: 'Lunes a Sábado 10:00 - 21:00 | Domingo 11:00 - 20:00',
    publicStatus: 'destacado',
    internalStatus: 'vencimientos_al_dia',
    documentationStatus: 'completa',
    protectionStatus: 'protegido',
    isFeatured: true,
    createdAt: '2024-01-20',
    updatedAt: '2024-03-10',
  },
  {
    id: '4',
    tenantId: 'homa_mall',
    name: 'Farmacia del Centro',
    slug: 'farmacia-del-centro',
    category: 'Farmacia',
    locationCode: 'L-120',
    description: 'Farmacia con amplio stock de medicamentos, cosmética y productos de salud. Atención personalizada y asesoramiento profesional.',
    logoUrl: '',
    photos: [],
    whatsapp: '5493541444444',
    instagram: '',
    schedule: 'Lunes a Domingo 08:00 - 22:00',
    publicStatus: 'verificado',
    internalStatus: 'documentacion_completa',
    documentationStatus: 'completa',
    protectionStatus: 'protegido',
    isFeatured: false,
    createdAt: '2024-01-10',
    updatedAt: '2024-02-20',
  },
  {
    id: '5',
    tenantId: 'homa_mall',
    name: 'SportMax',
    slug: 'sportmax',
    category: 'Deportes',
    subcategory: 'Indumentaria deportiva',
    locationCode: 'L-420',
    description: 'Todo para tu deporte favorito. Ropa, calzado y equipamiento de las mejores marcas deportivas.',
    logoUrl: '',
    photos: [],
    whatsapp: '5493541555555',
    instagram: 'sportmaxcpaz',
    schedule: 'Lunes a Sábado 09:00 - 21:00 | Domingo 10:00 - 20:00',
    publicStatus: 'publicado',
    internalStatus: 'documentacion_parcial',
    documentationStatus: 'parcial',
    protectionStatus: 'sin_cobertura',
    isFeatured: false,
    createdAt: '2024-02-15',
    updatedAt: '2024-03-12',
  },
  {
    id: '6',
    tenantId: 'homa_mall',
    name: 'Sushi Nori',
    slug: 'sushi-nori',
    category: 'Gastronomía',
    subcategory: 'Japonesa',
    locationCode: 'L-105',
    description: 'Auténtica cocina japonesa. Rolls, sashimi y bento preparados con ingredientes frescos cada día.',
    logoUrl: '',
    photos: [],
    whatsapp: '5493541666666',
    instagram: 'sushinoricpaz',
    schedule: 'Martes a Domingo 12:00 - 23:00',
    publicStatus: 'verificado',
    internalStatus: 'vencimientos_al_dia',
    documentationStatus: 'completa',
    protectionStatus: 'protegido',
    isFeatured: true,
    createdAt: '2024-01-25',
    updatedAt: '2024-03-08',
  },
];

export const MOCK_PROMOTIONS: Promotion[] = [
  {
    id: 'p1',
    tenantId: 'homa_mall',
    commerceId: '3',
    commerceName: 'Moda Bella',
    title: '30% OFF en toda la colección otoño',
    description: 'Aprovechá los mejores precios de la temporada. 30% de descuento en toda la ropa de otoño.',
    startsAt: '2024-04-01',
    endsAt: '2024-04-30',
    conditions: 'Válido solo en local. No acumulable con otras promociones.',
    status: 'aprobada',
    isFeatured: true,
    createdAt: '2024-03-25',
  },
  {
    id: 'p2',
    tenantId: 'homa_mall',
    commerceId: '1',
    commerceName: 'La Birra Craft',
    title: 'Happy Hour todos los miércoles',
    description: '2x1 en todas las pintas de 18 a 20 hs. ¡La mejor excusa para el after office!',
    startsAt: '2024-04-01',
    endsAt: '2024-06-30',
    conditions: 'Solo miércoles de 18:00 a 20:00 hs. Sujeto a disponibilidad.',
    status: 'aprobada',
    isFeatured: true,
    createdAt: '2024-03-20',
  },
  {
    id: 'p3',
    tenantId: 'homa_mall',
    commerceId: '2',
    commerceName: 'TechZone',
    title: 'Cuotas sin interés en celulares',
    description: '12 cuotas sin interés en todos los smartphones seleccionados.',
    startsAt: '2024-04-01',
    endsAt: '2024-04-15',
    conditions: 'Solo con tarjetas Visa y Mastercard adheridas. Consultar disponibilidad de stock.',
    status: 'aprobada',
    isFeatured: false,
    createdAt: '2024-03-28',
  },
];
